import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Box, Button } from "@mui/material";
import { useRouter } from "next/router";
import { CHAIN_NAMESPACES } from "@web3auth/base";
import { MetamaskAdapter } from "@web3auth/metamask-adapter";
import { ADAPTER_EVENTS } from "@web3auth/base";
import { useEffect, useLayoutEffect, useState } from "react";
import { web3auth, init } from "../components/web3Component";
import dynamic from "next/dynamic";

export default function Home() {
  const router = useRouter();
  let web3obj;

  useEffect(() => {
    web3obj = web3auth;
    console.log("web3obj", web3obj);

    if (typeof window !== "undefined") {
      const web3 = web3auth;
      init(web3);
    }
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>NFTThird You App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box
        display="flex"
        sx={{
          justifyContent: "center",
          justifyItems: "center",
          alignContent: "center",
          alignItems: "center",
          height: "100vh",

          color: "white",
          flexDirection: "column",
        }}
      >
        <Box
          sx={{
            justifyContent: "center",
            alignContent: "center",
            my: "5%",
            flexDirection: "column",
          }}
        >
          <div>
            <Button
              variant="contained"
              onClick={() => {
                router.push("/dashboard");
              }}
            >
              Start
            </Button>{" "}
          </div>
        </Box>
        <Box>
          {" "}
          <footer className={styles.footer}>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              Powered by{" "}
              <span className={styles.logo}>
                <Image
                  src="/vercel.svg"
                  alt="Vercel Logo"
                  width={72}
                  height={16}
                />
              </span>
            </a>
          </footer>
        </Box>
      </Box>
    </div>
  );
}
