import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Box, Button } from "@mui/material";
import { useRouter } from "next/router";
import { CHAIN_NAMESPACES } from "@web3auth/base";
import { MetamaskAdapter } from "@web3auth/metamask-adapter";
import { ADAPTER_EVENTS } from "@web3auth/base";
import { useEffect, useLayoutEffect, useState } from "react";
import { Web3Auth } from "@web3auth/web3auth";

export default function Home() {
  const router = useRouter();

  const [initialized, setInitialized] = useState(false);

  function subscribeAuthEvents(web3auth) {
    web3auth.on(ADAPTER_EVENTS.CONNECTED, (data) => {
      console.log(" CONNECTED Data", data);
    });
    web3auth.on(ADAPTER_EVENTS.CONNECTING, () => {
      console.log("connecting XXXXXXXXX");
    });

    web3auth.on(ADAPTER_EVENTS.DISCONNECTED, () => {
      console.log("disconnected");
    });

    web3auth.on(ADAPTER_EVENTS.ERRORED, (error) => {
      console.log("soerror or user have cancelled login request", error);
    });
  }

  const initializeModal = async (): Promise<any> => {
    console.log("*** InitModal ***");
    try {
      const { Web3Auth } = await import("@web3auth/web3auth");
      const web3auth = new Web3Auth({
        chainConfig: { chainNamespace: CHAIN_NAMESPACES.EIP155 },
        clientId: process.env.CLIENT_ID_WEB3AUTH,
      });
      subscribeAuthEvents(web3auth);
      await web3auth.initModal();
      setInitialized(true);

      return web3auth;
    } catch (error) {
      console.log("error", error);
      return error;
    }
  };

  useEffect(() => {
    initializeModal();
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>NFTThird You App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box
        display="flex"
        sx={{
          justifyContent: "center",
          justifyItems: "center",
          alignContent: "center",
          alignItems: "center",
          height: "100vh",

          color: "white",
          flexDirection: "column",
        }}
      >
        <Box
          sx={{
            justifyContent: "center",
            alignContent: "center",
            my: "5%",
            flexDirection: "column",
          }}
        >
          <div>
            <Button
              variant="contained"
              onClick={() => {
                if (initialized) {
                  Web3Auth.call;
                  console.log("Initialized");
                  router.push("/dashboard");
                }
              }}
            >
              Start
            </Button>{" "}
          </div>
        </Box>
        <Box>
          {" "}
          <footer className={styles.footer}>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              Powered by{" "}
              <span className={styles.logo}>
                <Image
                  src="/vercel.svg"
                  alt="Vercel Logo"
                  width={72}
                  height={16}
                />
              </span>
            </a>
          </footer>
        </Box>
      </Box>
    </div>
  );
}
