import Head from "next/head";
import Home from "../components/Home";
import dynamic from "next/dynamic";
const Header = dynamic(() => import("../components/Header"));
const Footer = dynamic(() => import("../components/Footer"));

import styles from "../styles/Home.module.css";
import { useRouter } from "next/router";

export default function Index() {
  const router = useRouter();
  return (
    <div className={styles.container}>
      <Head>
        <title>NFTThird You App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Home />
      <Footer />
    </div>
  );
}
